AWSTemplateFormatVersion: "2010-09-09"
Description: "Stack simple para crear una instancia EC2 en AWS"

Resources:
  MiInstanciaEC2:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      ImageId: ami-09e67e426f25ce0d7   # Amazon Linux 2 en us-east-1 (ajustar si querés)
      KeyName: mi-par-clave             # reemplazá con tu keypair existente
      SecurityGroups:
        - !Ref MiGrupoSeguridad

  MiGrupoSeguridad:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Permite SSH desde cualquier origen"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
